export const TEACHER_GET_ALL_REQUEST = "TEACHER_GET_ALL_REQUEST";
export const TEACHER_GET_ALL_SUCCESS = "TEACHER_GET_ALL_SUCCESS";
export const TEACHER_GET_ALL_FAIL = "TEACHER_GET_ALL_FAIL";

export const STUDENT_GET_ALL_REQUEST = "STUDENT_GET_ALL_REQUEST";
export const STUDENT_GET_ALL_SUCCESS = "STUDENT_GET_ALL_SUCCESS";
export const STUDENT_GET_ALL_FAIL = "STUDENT_GET_ALL_FAIL";


export const TEACHER_POST_ALL_REQUEST = "TEACHER_POST_ALL_REQUEST";
export const TEACHER_POST_ALL_SUCCESS = "TEACHER_POST_ALL_SUCCESS";
export const TEACHER_POST_ALL_FAIL = "TEACHER_POST_ALL_FAIL";