export const TEACHER_GET_ALL_REQUEST = "TEACHER_GET_ALL_REQUEST";
export const TEACHER_GET_ALL_SUCCESS = "TEACHER_GET_ALL_SUCCESS";
export const TEACHER_GET_ALL_FAIL = "TEACHER_GET_ALL_FAIL";
export const TEACHER_GET_ALL_CREATED = "TEACHER_GET_ALL_CREATED";
export const TEACHER_GET_ALL_DELETED = "TEACHER_GET_ALL_DELETED";

export const STUDENT_GET_ALL_REQUEST = "STUDENT_GET_ALL_REQUEST";
export const STUDENT_GET_ALL_SUCCESS = "STUDENT_GET_ALL_SUCCESS";
export const STUDENT_GET_ALL_FAIL = "STUDENT_GET_ALL_FAIL";
export const STUDENT_GET_ALL_CREATED = "STUDENT_GET_ALL_CREATED";
export const STUDENT_GET_ALL_DELETED = "STUDENT_GET_ALL_DELETED";

export const GROUPS_GET_ALL_REQUEST = "GROUPS_GET_ALL_REQUEST";
export const GROUPS_GET_ALL_SUCCESS = "GROUPS_GET_ALL_SUCCESS";
export const GROUPS_GET_ALL_FAIL = "GROUPS_GET_ALL_FAIL";
export const GROUPS_GET_ALL_CREATED = "GROUPS_GET_ALL_CREATED";
export const GROUPS_GET_ALL_DELETED = "GROUPS_GET_ALL_DELETED";

export const GROUPS_GET_ONE_REQUEST = "GROUPS_GET_ONE_REQUEST";
export const GROUPS_GET_ONE_SUCCESS = "GROUPS_GET_ONE_SUCCESS";
export const GROUPS_GET_ONE_FAIL = "GROUPS_GET_ONE_FAIL";
export const GROUPS_GET_ONE_CREATED = "GROUPS_GET_ONE_CREATED";
export const GROUPS_POST_STUDENT_ADD = "GROUPS_POST_STUDENT_ADD";
export const GROUPS_POST_STUDENT_REMOVED = "GROUPS_POST_STUDENT_REMOVED";

export const GROUPS_TIMES_GET_ONE_REQUEST = "GROUPS_TIMES_GET_ONE_REQUEST";
export const GROUPS_TIMES_GET_ONE_SUCCESS = "GROUPS_TIMES_GET_ONE_SUCCESS";
export const GROUPS_TIMES_GET_ONE_FAIL = "GROUPS_TIMES_GET_ONE_FAIL";
export const GROUPS_TIMES_GET_ONE_CREATED = "GROUPS_TIMES_GET_ONE_CREATED";

export const SUBJECTS_GET_ALL_REQUEST = "SUBJECTS_GET_ALL_REQUEST";
export const SUBJECTS_GET_ALL_SUCCESS = "SUBJECTS_GET_ALL_SUCCESS";
export const SUBJECTS_GET_ALL_FAIL = "SUBJECTS_GET_ALL_FAIL";

export const LOCATION_GET_ALL_REQUEST = "LOCATION_GET_ALL_REQUEST";
export const LOCATION_GET_ALL_SUCCESS = "LOCATION_GET_ALL_SUCCESS";
export const LOCATION_GET_ALL_FAIL = "LOCATION_GET_ALL_FAIL";
export const LOCATION_GET_ALL_CREATED = "LOCATION_GET_ALL_CREATED";

export const SEND_MESSAGE = "SEND_MESSAGE";
export const HOMEWORK_CREATED = "HOMEWORK_CREATED";
