export const TEACHER_GET_ALL_REQUEST = "TEACHER_GET_ALL_REQUEST";
export const TEACHER_GET_ALL_SUCCESS = "TEACHER_GET_ALL_SUCCESS";
export const TEACHER_GET_ALL_FAIL = "TEACHER_GET_ALL_FAIL";

export const STUDENT_GET_ALL_REQUEST = "STUDENT_GET_ALL_REQUEST";
export const STUDENT_GET_ALL_SUCCESS = "STUDENT_GET_ALL_SUCCESS";
export const STUDENT_GET_ALL_FAIL = "STUDENT_GET_ALL_FAIL";

export const GROUPS_GET_ALL_REQUEST = "GROUPS_GET_ALL_REQUEST";
export const GROUPS_GET_ALL_SUCCESS = "GROUPS_GET_ALL_SUCCESS";
export const GROUPS_GET_ALL_FAIL = "GROUPS_GET_ALL_FAIL";

export const GROUPS_GET_ONE_REQUEST = "GROUPS_GET_ONE_REQUEST";
export const GROUPS_GET_ONE_SUCCESS = "GROUPS_GET_ONE_SUCCESS";
export const GROUPS_GET_ONE_FAIL = "GROUPS_GET_ONE_FAIL";


export const GROUPS_TIMES_GET_ONE_REQUEST = "GROUPS_TIMES_GET_ONE_REQUEST";
export const GROUPS_TIMES_GET_ONE_SUCCESS = "GROUPS_TIMES_GET_ONE_SUCCESS";
export const GROUPS_TIMES_GET_ONE_FAIL = "GROUPS_TIMES_GET_ONE_FAIL";


export const TEACHER_POST_ALL_REQUEST = "TEACHER_POST_ALL_REQUEST";
export const TEACHER_POST_ALL_SUCCESS = "TEACHER_POST_ALL_SUCCESS";
export const TEACHER_POST_ALL_FAIL = "TEACHER_POST_ALL_FAIL";

export const GROUPS_POST_ALL_REQUEST = "GROUPS_POST_ALL_REQUEST";
export const GROUPS_POST_ALL_SUCCESS = "GROUPS_POST_ALL_SUCCESS";
export const GROUPS_POST_ALL_FAIL = "GROUPS_POST_ALL_FAIL";
