export const TEACHERS_FETCHED = "TEACHERS_FETCHED";
export const TEACHER_FETCHING = "TEACHER_FETCHING";
export const TEACHER_FETCHING_ERROR = "TEACHER_FETCHING_ERROR";

export const TEACHERS_CREATED = "TEACHERS_CREATED";
