export const GROUPS_GET_ALL_REQUEST = "GROUPS_GET_ALL_REQUEST";
export const GROUPS_GET_ALL_SUCCESS = "GROUPS_GET_ALL_SUCCESS";
export const GROUPS_GET_ALL_FAIL = "GROUPS_GET_ALL_FAIL";



export const GROUPS_GET_ONE_REQUEST = "GROUPS_GET_ONE_REQUEST";
export const GROUPS_GET_ONE_SUCCESS = "GROUPS_GET_ONE_SUCCESS";
export const GROUPS_GET_ONE_FAIL = "GROUPS_GET_ONE_FAIL";


export const SEND_MESSAGE = "SEND_MESSAGE";


// export const MESSAGE_PUT_ONE_REQUEST = "MESSAGE_PUT_ONE_REQUEST";
// export const MESSAGE_PUT_ONE_SUCCESS = "MESSAGE_PUT_ONE_SUCCESS";
// export const MESSAGE_PUT_ONE_FAIL = "MESSAGE_PUT_ONE_FAIL";
