export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

// export const TEACHERS_FETCHED = "TEACHERS_FETCHED";
// export const TEACHER_FETCHING = "TEACHER_FETCHING";
// export const TEACHER_FETCHING_ERROR = "TEACHER_FETCHING_ERROR";

// export const TEACHERS_CREATED = "TEACHERS_CREATED";
